name: Test Custom Action

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run forked action
        id: analytics
        uses: gdegani/pull-request-analytics-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.A_TOKEN_OF_MINE }}
          GITHUB_REPO_FOR_ISSUE: pull-request-analytics-action
          GITHUB_OWNER_FOR_ISSUE: gdegani
          GITHUB_OWNERS_REPOS: ${{ vars.TEST_GITHUB_OWNERS_REPOS }}
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Rome"
          REPORT_PERIOD: ${{ vars.TEST_REPORT_PERIOD }}
          
          SHOW_STATS_TYPES: ${{ vars.TEST_SHOW_STATS_TYPES }}
          EXECUTION_OUTCOME: ${{ vars.TEST_EXECUTION_OUTCOME }}
          AGGREGATE_VALUE_METHODS: ${{ vars.TEST_AGGREGATE_VALUE_METHODS }}
          HIDE_USERS: ${{ vars.TEST_HIDE_USERS }}
          PERIOD_SPLIT_UNIT: ${{ vars.TEST_PERIOD_SPLIT_UNIT }}
          ALLOW_ANALYTICS: false
      - name: Publish
        run: |
          mkdir -p report

          # Write MARKDOWN output (existing)
          printf '%s\n' "${{ steps.analytics.outputs.markdown }}" > report/report.md
          # Append markdown to the step summary
          echo '## Report (Markdown)' >> $GITHUB_STEP_SUMMARY
          cat report/report.md >> $GITHUB_STEP_SUMMARY

          # Write TSV output safely (preserve newlines)
          printf '%s\n' "${{ steps.analytics.outputs.tsv }}" > report/report.tsv

          # Append TSV to the step summary inside a fenced code block for readability
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '## Report (TSV)' >> $GITHUB_STEP_SUMMARY
          echo '```tsv' >> $GITHUB_STEP_SUMMARY
          cat report/report.tsv >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-analytics-reports
          path: |
            report/report.tsv
            report/report.md