name: Test Custom Action

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run forked action
        id: analytics
        uses: gdegani/pull-request-analytics-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.A_TOKEN_OF_MINE }}
          GITHUB_REPO_FOR_ISSUE: ${{ vars.TEST_GITHUB_REPO_FOR_ISSUE }}
          GITHUB_OWNER_FOR_ISSUE: ${{ vars.TEST_GITHUB_OWNER_FOR_ISSUE }}
          GITHUB_OWNERS_REPOS: ${{ vars.TEST_GITHUB_OWNERS_REPOS }}
          ORGANIZATIONS: ${{ vars.TEST_ORGANIZATIONS }}
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Rome"
          REPORT_PERIOD: ${{ vars.TEST_REPORT_PERIOD }}
          
          SHOW_STATS_TYPES: ${{ vars.TEST_SHOW_STATS_TYPES }}
          EXECUTION_OUTCOME: ${{ vars.TEST_EXECUTION_OUTCOME }}
          AGGREGATE_VALUE_METHODS: ${{ vars.TEST_AGGREGATE_VALUE_METHODS }}
          HIDE_USERS: ${{ vars.TEST_HIDE_USERS }}
          PERIOD_SPLIT_UNIT: ${{ vars.TEST_PERIOD_SPLIT_UNIT }}
          ALLOW_ANALYTICS: false
      - name: Publish
        run: |
          mkdir -p report

          # Write JSON output safely (preserve newlines) only if it exists
          if [ -n '${{ steps.analytics.outputs.json_collection }}' ]; then
          echo '${{ steps.analytics.outputs.json_collection }}' > report/report.json
          fi
          
          # Write TSV output only if it exists
          if [ -n '${{ steps.analytics.outputs.tsv }}' ]; then
          printf '%s' '${{ steps.analytics.outputs.tsv }}' > report/report.tsv
          fi
      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-analytics-reports
          path: |
            report/report.json
            report/report.tsv